Repository KonferCA/SPUR-Onboard, pull requests merged in 2024-11, with the labels that each got.

#40 add spur team as codeowners
  .github/CODEOWNERS
Labels: documentation

#47 Fix user validation
  backend/internal/middleware/req_validator.go
  backend/internal/server/auth.go
  backend/internal/server/handler_helpers.go
  backend/internal/server/types.go
Labels: bug

#38 Feat/27/anchor links
  frontend/.prettierrc.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/AnchorLinks.tsx
  frontend/src/components/ScrollLink.tsx
  frontend/src/components/index.ts
  frontend/src/pages/Landing.tsx
  frontend/src/utils/index.ts
  frontend/src/utils/scroll.ts
  frontend/tsconfig.app.json
  frontend/vite.config.ts
  frontend/vitest.config.ts
  src/types/common.ts
  src/types/index.ts
Labels: enhancement

#49 move frontend custom types out of root
  frontend/src/types/common.ts
  frontend/src/types/index.ts
Labels: bug

#46 Fix workflows
  .github/workflows/backend/test-backend.yml
  .github/workflows/deploy-preview-backend.yml
  .github/workflows/deploy-preview-frontend.yml
  .github/workflows/test-backend.yml
  .github/workflows/test-frontend.yml
  backend/.gitignore
  backend/Makefile
  backend/README.md
  frontend/index.html
Labels: bug, enhancement

#51 remove cache opt when setting up node
  .github/workflows/deploy-preview-frontend.yml
Labels: bug

#57 rename go module name
  backend/go.mod
  backend/internal/jwt/generate.go
  backend/internal/jwt/jwt_test.go
  backend/internal/jwt/types.go
  backend/internal/middleware/jwt.go
  backend/internal/middleware/jwt_test.go
  backend/internal/middleware/req_validator.go
  backend/internal/server/auth.go
  backend/internal/server/company.go
  backend/internal/server/company_documents.go
  backend/internal/server/company_financials.go
  backend/internal/server/company_questions_answers.go
  backend/internal/server/employee.go
  backend/internal/server/funding_transactions.go
  backend/internal/server/handler_helpers.go
  backend/internal/server/index.go
  backend/internal/server/meetings.go
  backend/internal/server/projects.go
  backend/internal/server/resource_request.go
  backend/internal/server/startup.go
  backend/internal/server/tag.go
  backend/internal/server/types.go
  backend/main.go
Labels: enhancement

#55 Update project routes
  backend/internal/server/index.go
  backend/internal/server/projects.go
Labels: bug

#54 Resolve security issue by using strconv.Atoi without upper/lower bounds
  backend/internal/server/company_financials.go
Labels: bug
